export const PROTOCOL_VERSION = 1;
export const DEFAULT_BROKER_HOST = "127.0.0.1";
export const DEFAULT_BROKER_PORT = 17345;
export const MAX_SELECTED_TEXT_BYTES = 50 * 1024;
export const MAX_SELECTED_HTML_BYTES = 100 * 1024;
export const TARGET_HEARTBEAT_INTERVAL_MS = 5_000;
export const TARGET_STALE_AFTER_MS = 15_000;
export const DIAGNOSTIC_LOG_LIMIT = 50;
