export const PROTOCOL_VERSION = 1;
export const DEFAULT_DIRECT_SESSION_HOST = "127.0.0.1";
export const MAX_SELECTED_TEXT_BYTES = 50 * 1024;
export const MAX_SELECTED_HTML_BYTES = 100 * 1024;
export const DIAGNOSTIC_LOG_LIMIT = 50;
